default:
  target: dev
  outputs:
    dev:
      type: snowflake
      private_key_path: /root/.ssh/snowflake.p8
      account: "{{ env_var('ACCOUNT') }}"
      user: "{{ env_var('USER') }}"
      role: "{{ env_var('ROLE') }}"
      warehouse: "{{ env_var('WAREHOUSE') }}"
      database: "{{ env_var('DB') }}"
      schema: "{{ env_var('SCHEMA') }}"
      threads: 1
